### ISSUE TITLE
bundle exec rake db:migrate error

### ISSUE THREAD

**Issue by eugenehp** [evercam/evercam-api#380]
```
bundle exec rake db:migrate
COMMAND  PID    USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
ruby    3226 vagrant    7u  IPv4  15457      0t0  TCP *:10453 (LISTEN)
localhost - - [29/Jul/2015:08:33:16 UTC] "PUT /evercam-camera-assets HTTP/1.1" 200 0
- -> /evercam-camera-assets
localhost - - [29/Jul/2015:08:33:16 UTC] "PUT /evercam-public-assets HTTP/1.1" 200 0
- -> /evercam-public-assets
WARNING: Unable to create the evercam user in the postgres://localhost/evercam_dev database as Ireland could not be found in the countries table.
WARNING: Unable to create the evercam remembrance camera in the postgres://localhost/evercam_dev database as the evercam user could not be found.
rake aborted!
Sequel::DatabaseError: PG::DuplicateTable: ERROR:  relation "apps" already exists
/home/vagrant/.rvm/gems/ruby-2.2.0/gems/sequel-4.23.0/lib/sequel/adapters/postgres.rb:180:in `async_exec'
/home/vagrant/.rvm/gems/ruby-2.2.0/gems/sequel-4.23.0/lib/sequel/adapters/postgres.rb:180:in `block in execute_query'
/home/vagrant/.rvm/gems/ruby-2.2.0/gems/sequel-4.23.0/lib/sequel/database/logging.rb:33:in `log_yield'
/home/vagrant/.rvm/gems/ruby-2.2.0/gems/sequel-4.23.0/lib/sequel/adapters/postgres.rb:180:in `execute_query'
/home/vagrant/.rvm/gems/ruby-2.2.0/gems/sequel-4.23.0/lib/sequel/adapters/postgres.rb:167:in `block in execute'
/home/vagrant/.rvm/gems/ruby-2.2.0/gems/sequel-4.23.0/lib/sequel/adapters/postgres.rb:143:in `check_disconnect_errors'
/home/vagrant/.rvm/gems/ruby-2.2.0/gems/sequel-4.23.0/lib/sequel/adapters/postgres.rb:167:in `execute'
/home/vagrant/.rvm/gems/ruby-2.2.0/gems/sequel-4.23.0/lib/sequel/adapters/postgres.rb:512:in `_execute'
/home/vagrant/.rvm/gems/ruby-2.2.0/gems/sequel-4.23.0/lib/sequel/adapters/postgres.rb:336:in `block (2 levels) in execute'
/home/vagrant/.rvm/gems/ruby-2.2.0/gems/sequel-4.23.0/lib/sequel/adapters/postgres.rb:533:in `check_database_errors'
/home/vagrant/.rvm/gems/ruby-2.2.0/gems/sequel-4.23.0/lib/sequel/adapters/postgres.rb:336:in `block in execute'
/home/vagrant/.rvm/gems/ruby-2.2.0/gems/sequel-4.23.0/lib/sequel/database/connecting.rb:250:in `block in synchronize'
/home/vagrant/.rvm/gems/ruby-2.2.0/gems/sequel-4.23.0/lib/sequel/connection_pool/threaded.rb:99:in `hold'
/home/vagrant/.rvm/gems/ruby-2.2.0/gems/sequel-4.23.0/lib/sequel/database/connecting.rb:250:in `synchronize'
/home/vagrant/.rvm/gems/ruby-2.2.0/gems/sequel-4.23.0/lib/sequel/adapters/postgres.rb:336:in `execute'
/home/vagrant/.rvm/gems/ruby-2.2.0/gems/sequel-4.23.0/lib/sequel/database/query.rb:50:in `execute_dui'
/home/vagrant/.rvm/gems/ruby-2.2.0/gems/sequel-4.23.0/lib/sequel/database/query.rb:43:in `execute_ddl'
/home/vagrant/.rvm/gems/ruby-2.2.0/gems/sequel-4.23.0/lib/sequel/database/schema_methods.rb:641:in `create_table_from_generator'
/home/vagrant/.rvm/gems/ruby-2.2.0/gems/sequel-4.23.0/lib/sequel/database/schema_methods.rb:195:in `create_table'
migrations/20150722062320_create_apps.rb:3:in `block (2 levels) in <top (required)>'
/home/vagrant/.rvm/gems/ruby-2.2.0/gems/sequel-4.23.0/lib/sequel/extensions/migration.rb:100:in `instance_eval'
/home/vagrant/.rvm/gems/ruby-2.2.0/gems/sequel-4.23.0/lib/sequel/extensions/migration.rb:100:in `apply'
/home/vagrant/.rvm/gems/ruby-2.2.0/gems/sequel-4.23.0/lib/sequel/extensions/migration.rb:654:in `block (2 levels) in run'
/home/vagrant/.rvm/gems/ruby-2.2.0/gems/sequel-4.23.0/lib/sequel/database/transactions.rb:134:in `_transaction'
/home/vagrant/.rvm/gems/ruby-2.2.0/gems/sequel-4.23.0/lib/sequel/database/transactions.rb:108:in `block in transaction'
/home/vagrant/.rvm/gems/ruby-2.2.0/gems/sequel-4.23.0/lib/sequel/database/connecting.rb:250:in `block in synchronize'
/home/vagrant/.rvm/gems/ruby-2.2.0/gems/sequel-4.23.0/lib/sequel/connection_pool/threaded.rb:103:in `hold'
/home/vagrant/.rvm/gems/ruby-2.2.0/gems/sequel-4.23.0/lib/sequel/database/connecting.rb:250:in `synchronize'
/home/vagrant/.rvm/gems/ruby-2.2.0/gems/sequel-4.23.0/lib/sequel/database/transactions.rb:97:in `transaction'
/home/vagrant/.rvm/gems/ruby-2.2.0/gems/sequel-4.23.0/lib/sequel/extensions/migration.rb:464:in `checked_transaction'
/home/vagrant/.rvm/gems/ruby-2.2.0/gems/sequel-4.23.0/lib/sequel/extensions/migration.rb:653:in `block in run'
/home/vagrant/.rvm/gems/ruby-2.2.0/gems/sequel-4.23.0/lib/sequel/extensions/migration.rb:650:in `each'
/home/vagrant/.rvm/gems/ruby-2.2.0/gems/sequel-4.23.0/lib/sequel/extensions/migration.rb:650:in `run'
/home/vagrant/.rvm/gems/ruby-2.2.0/gems/sequel-4.23.0/lib/sequel/extensions/migration.rb:391:in `run'
/vagrant/evercam-api/rakefile:19:in `block (3 levels) in <top (required)>'
/vagrant/evercam-api/rakefile:17:in `each'
/vagrant/evercam-api/rakefile:17:in `block (2 levels) in <top (required)>'
/home/vagrant/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `eval'
/home/vagrant/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `<main>'
PG::DuplicateTable: ERROR:  relation "apps" already exists
/home/vagrant/.rvm/gems/ruby-2.2.0/gems/sequel-4.23.0/lib/sequel/adapters/postgres.rb:180:in `async_exec'
/home/vagrant/.rvm/gems/ruby-2.2.0/gems/sequel-4.23.0/lib/sequel/adapters/postgres.rb:180:in `block in execute_query'
/home/vagrant/.rvm/gems/ruby-2.2.0/gems/sequel-4.23.0/lib/sequel/database/logging.rb:33:in `log_yield'
/home/vagrant/.rvm/gems/ruby-2.2.0/gems/sequel-4.23.0/lib/sequel/adapters/postgres.rb:180:in `execute_query'
/home/vagrant/.rvm/gems/ruby-2.2.0/gems/sequel-4.23.0/lib/sequel/adapters/postgres.rb:167:in `block in execute'
/home/vagrant/.rvm/gems/ruby-2.2.0/gems/sequel-4.23.0/lib/sequel/adapters/postgres.rb:143:in `check_disconnect_errors'
/home/vagrant/.rvm/gems/ruby-2.2.0/gems/sequel-4.23.0/lib/sequel/adapters/postgres.rb:167:in `execute'
/home/vagrant/.rvm/gems/ruby-2.2.0/gems/sequel-4.23.0/lib/sequel/adapters/postgres.rb:512:in `_execute'
/home/vagrant/.rvm/gems/ruby-2.2.0/gems/sequel-4.23.0/lib/sequel/adapters/postgres.rb:336:in `block (2 levels) in execute'
/home/vagrant/.rvm/gems/ruby-2.2.0/gems/sequel-4.23.0/lib/sequel/adapters/postgres.rb:533:in `check_database_errors'
/home/vagrant/.rvm/gems/ruby-2.2.0/gems/sequel-4.23.0/lib/sequel/adapters/postgres.rb:336:in `block in execute'
/home/vagrant/.rvm/gems/ruby-2.2.0/gems/sequel-4.23.0/lib/sequel/database/connecting.rb:250:in `block in synchronize'
/home/vagrant/.rvm/gems/ruby-2.2.0/gems/sequel-4.23.0/lib/sequel/connection_pool/threaded.rb:99:in `hold'
/home/vagrant/.rvm/gems/ruby-2.2.0/gems/sequel-4.23.0/lib/sequel/database/connecting.rb:250:in `synchronize'
/home/vagrant/.rvm/gems/ruby-2.2.0/gems/sequel-4.23.0/lib/sequel/adapters/postgres.rb:336:in `execute'
/home/vagrant/.rvm/gems/ruby-2.2.0/gems/sequel-4.23.0/lib/sequel/database/query.rb:50:in `execute_dui'
/home/vagrant/.rvm/gems/ruby-2.2.0/gems/sequel-4.23.0/lib/sequel/database/query.rb:43:in `execute_ddl'
/home/vagrant/.rvm/gems/ruby-2.2.0/gems/sequel-4.23.0/lib/sequel/database/schema_methods.rb:641:in `create_table_from_generator'
/home/vagrant/.rvm/gems/ruby-2.2.0/gems/sequel-4.23.0/lib/sequel/database/schema_methods.rb:195:in `create_table'
migrations/20150722062320_create_apps.rb:3:in `block (2 levels) in <top (required)>'
/home/vagrant/.rvm/gems/ruby-2.2.0/gems/sequel-4.23.0/lib/sequel/extensions/migration.rb:100:in `instance_eval'
/home/vagrant/.rvm/gems/ruby-2.2.0/gems/sequel-4.23.0/lib/sequel/extensions/migration.rb:100:in `apply'
/home/vagrant/.rvm/gems/ruby-2.2.0/gems/sequel-4.23.0/lib/sequel/extensions/migration.rb:654:in `block (2 levels) in run'
/home/vagrant/.rvm/gems/ruby-2.2.0/gems/sequel-4.23.0/lib/sequel/database/transactions.rb:134:in `_transaction'
/home/vagrant/.rvm/gems/ruby-2.2.0/gems/sequel-4.23.0/lib/sequel/database/transactions.rb:108:in `block in transaction'
/home/vagrant/.rvm/gems/ruby-2.2.0/gems/sequel-4.23.0/lib/sequel/database/connecting.rb:250:in `block in synchronize'
/home/vagrant/.rvm/gems/ruby-2.2.0/gems/sequel-4.23.0/lib/sequel/connection_pool/threaded.rb:103:in `hold'
/home/vagrant/.rvm/gems/ruby-2.2.0/gems/sequel-4.23.0/lib/sequel/database/connecting.rb:250:in `synchronize'
/home/vagrant/.rvm/gems/ruby-2.2.0/gems/sequel-4.23.0/lib/sequel/database/transactions.rb:97:in `transaction'
/home/vagrant/.rvm/gems/ruby-2.2.0/gems/sequel-4.23.0/lib/sequel/extensions/migration.rb:464:in `checked_transaction'
/home/vagrant/.rvm/gems/ruby-2.2.0/gems/sequel-4.23.0/lib/sequel/extensions/migration.rb:653:in `block in run'
/home/vagrant/.rvm/gems/ruby-2.2.0/gems/sequel-4.23.0/lib/sequel/extensions/migration.rb:650:in `each'
/home/vagrant/.rvm/gems/ruby-2.2.0/gems/sequel-4.23.0/lib/sequel/extensions/migration.rb:650:in `run'
/home/vagrant/.rvm/gems/ruby-2.2.0/gems/sequel-4.23.0/lib/sequel/extensions/migration.rb:391:in `run'
/vagrant/evercam-api/rakefile:19:in `block (3 levels) in <top (required)>'
/vagrant/evercam-api/rakefile:17:in `each'
/vagrant/evercam-api/rakefile:17:in `block (2 levels) in <top (required)>'
/home/vagrant/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `eval'
/home/vagrant/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)

```

**Comment by mosic** [comment]
Fixed in https://github.com/evercam/evercam-api/pull/386
